language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install: python setup.py install

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 testmachine -w; fi
  - pip install pytest pytest-cov coveralls pyflakes

script:
  - pyflakes testmachine
  - py.test -v testmachine --cov=testmachine

after_success:
  - coveralls
